name: Deploy to Static.app

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Static.app
        uses: designmodo/static-app-deploy-action@main
        with:
          # CORRECTION ICI : "api-key" avec un tiret, pas un underscore
          api-key: ${{ secrets.STATIC_APP_API_KEY }}
          root_directory: '.'
